### ISSUE TITLE
Basic auth required

### ISSUE THREAD

**Issue by alexellis** [affix/openfaas-sqs-connector#1]
Hi @affix,

I'd like to list this connector and to promote it, but I can't right now since there appears to be no support for basic auth secrets and we don't want to encourage or recommend that anyone run OpenFaaS without any form of authentication.

Can you look at how the other connectors do this and update the code/YAML?

Alex

**Comment by affix** [comment]
Fixed by providing auth secrets in the k8s Yaml

**Comment by affix** [comment]
Fixed, thanks @alexellis
